apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kaau
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: KAAU
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: KAAU
    spec:
      containers:
      - args:
        - -c
        - while true; do echo hello; sleep 10;done
        command:
        - /bin/bash
        image: yogeshkunjir/kaau:0.0.0.2
        imagePullPolicy: IfNotPresent
        name: kaau
        ports:
        - containerPort: 3333
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 3333
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "1"
          requests:
            cpu: 25m
            memory: 126Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: kaau-admin
      serviceAccountName: kaau-admin
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kaau-admin 
  namespace: default
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kaau-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kaau-cluster-role
subjects:
- kind: ServiceAccount
  name: kaau-admin
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kaau-cluster-role
rules:
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  - namespaces
  - roles
  verbs:
  - create
  - get
  - delete
  - list
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  - clusterroles
  - rolebindings
  - clusterrolebindings
  verbs:
  - create
  - get
  - delete
  - list
  - update